### ISSUE TITLE
Utilização de text block

### ISSUE THREAD

**Issue by arthurs159** [LenizaSouza/planning-day#1]
Ei Leniza, tudo bem?

Vendo seu projeto, percebo que você escreve query concatenando vários pedaços de Strings, como por exemplo:
![image](https://user-images.githubusercontent.com/77133022/206037307-0cd9aff2-1230-4034-92fe-00223c626617.png)
Acredito que seja interessante a utilização do text block em todos os lugares do seu projeto que tem esse padrão.

Qualquer dúvida, só me chamar, beleza? : )

**Comment by LenizaSouza** [comment]
Estou usando o java 11 nesse projeto, por isso não será possível a utilização do text block. Mas anotei a dica para o próximo projeto, obrigada.
